// `src/icon-paths.ts` 를 `lucide-static` 에서 생성한다. `--check` 는 생성 대신 대조만 한다.
//
// ## 왜 생성하는가 — 콘솔은 CDN 을 못 쓴다
//
// `manager-ui.ts` 의 규약은 「No CDN, no external font, no remote anything」이다. 방화벽 콘솔이
// 로드 시점에 제3자에게서 코드를 받아오면 그 제3자가 「운영자가 자기 네트워크에 대해 믿는 것」의
// 저자가 된다 — 게다가 이 페이지는 **네트워크가 고장난 날에 열리는 페이지**다.
//
// 그래서 아이콘은 빌드 시점에 라이브러리에서 꺼내 소스로 커밋한다. 런타임 의존성은 0 개이고,
// `lucide-static` 은 devDependency 로만 존재한다.
//
// ## `--check` 가 잡는 두 가지
//
//   1. **라이브러리에 없는 이름.** Lucide 는 버전 사이에 아이콘을 개명한다. 없는 이름은 오류가
//      아니라 **빈 칸**으로 렌더된다 — 이 저장소가 반복해서 당한 침묵과 같은 종류다.
//   2. **생성물이 낡음.** `src/icon-names.ts` 에서 이름을 지우고 다시 만들지 않으면 tsc 는
//      통과하고(모자란 쪽만 운다) 쓰지 않는 심볼이 페이지에 남는다.
//
// 두 검사의 알려진 양성은 `src/icons.test.ts` 가 들고 있다.
//
// 사용:
//   node scripts/build-icons.ts            # 생성
//   node scripts/build-icons.ts --check    # 대조만 (CI·훅용)
import { readFileSync, writeFileSync } from "node:fs";
import { ICON_NAMES } from "../src/icon-names.ts";

const LIB = "node_modules/lucide-static/icons";
const OUT = "src/icon-paths.ts";

/**
 * lucide-static 의 SVG 파일에서 **안쪽 마크업만** 꺼낸다.
 *
 * 바깥 `<svg>` 는 버리고 다시 쓴다: 라이브러리는 `width="24" height="24"` 를 박아 두는데, 이
 * 콘솔의 아이콘은 옆 글자를 따라 커져야 하므로 크기는 CSS(`1em`)가 정한다. 라이선스 주석도
 * 버린다 — 스프라이트에 스무 번 반복될 이유가 없고, 라이선스는 `package.json` 의 의존성이 이미
 * 기록한다.
 *
 * 내보내는 이유는 `icons.test.ts` 가 **알려진 양성**(감싸이지 않은 입력)으로 고정하기 때문이다.
 */
export function innerMarkup(svg: string): string {
  const start = svg.indexOf("<svg");
  const open = start === -1 ? -1 : svg.indexOf(">", start);
  const close = svg.lastIndexOf("</svg>");
  if (open === -1 || close === -1 || close < open) {
    throw new Error("이 파일은 <svg> 하나로 감싸여 있지 않다");
  }
  return svg
    .slice(open + 1, close)
    .replace(/<!--[\s\S]*?-->/g, "")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l !== "")
    .join("");
}

function generate(): string {
  const missing: string[] = [];
  const entries: string[] = [];
  for (const name of ICON_NAMES) {
    let svg: string;
    try {
      svg = readFileSync(`${LIB}/${name}.svg`, "utf8");
    } catch {
      missing.push(name);
      continue;
    }
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(innerMarkup(svg))},`);
  }
  if (missing.length) {
    console.error(`[icons] lucide-static 에 없는 이름 ${missing.length}개:`);
    for (const m of missing) console.error(`  · ${m}`);
    console.error("");
    console.error("이 이름들은 **빈 칸으로 렌더된다** — 오류가 아니라 침묵이다.");
    console.error("Lucide 를 올렸다면 개명됐을 수 있다. 새 이름을 찾아 src/icon-names.ts 를 고칠 것.");
    process.exit(1);
  }

  const version = JSON.parse(
    readFileSync("node_modules/lucide-static/package.json", "utf8"),
  ).version as string;

  return `// GENERATED by scripts/build-icons.ts from lucide-static ${version} (ISC) — do not edit.
// 다시 만들려면: npm run icons     ·     대조만: npm run icons:check
import type { IconName } from "./icon-names.ts";

/** 아이콘 이름 → SVG 안쪽 마크업. 바깥 \`<svg>\` 는 \`icons.ts\` 가 그린다. */
export const ICON_PATHS: Record<IconName, string> = {
${entries.join("\n")}
};
`;
}

const next = generate();

if (!process.argv.includes("--check")) {
  writeFileSync(OUT, next);
  console.log(`[icons] ${OUT} — 아이콘 ${ICON_NAMES.length}종`);
} else {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* 없으면 아래 비교에서 걸린다 */
  }
  if (current !== next) {
    console.error(`[icons] ${OUT} 가 src/icon-names.ts · lucide-static 과 다르다.`);
    console.error("        npm run icons 를 돌리고 결과를 커밋할 것.");
    process.exit(1);
  }
  console.log(`[icons] ${OUT} 최신 · 아이콘 ${ICON_NAMES.length}종 전부 lucide-static 에 실재`);
}
